### ISSUE TITLE
配置中心为空，bls-config中的config字段为空数组

### ISSUE THREAD

**Issue by a08381** [mscststs/BLS#15]
![屏幕快照 2020-04-22 下午12 00 43](https://user-images.githubusercontent.com/2505002/79939147-efb51300-8490-11ea-9df1-6d011da49a22.png)

可否给一个config字段的json表？

**Comment by mscststs** [comment]
咦，你这是怎么操作出来的，很神奇

**Comment by a08381** [comment]
> 咦，你这是怎么操作出来的，很神奇

OSX系統下使用源碼編譯程式文件變成這樣的

**Comment by mscststs** [comment]
> > 咦，你这是怎么操作出来的，很神奇
> 
> OSX系統下使用源碼編譯程式文件變成這樣的

试下我之前打过的这个 https://github.com/mscststs/BLS/releases/tag/0.1.8

**Comment by a08381** [comment]
> > > 咦，你这是怎么操作出来的，很神奇
> > 
> > 
> > OSX系統下使用源碼編譯程式文件變成這樣的
> 
> 试下我之前打过的这个 https://github.com/mscststs/BLS/releases/tag/0.1.8

说起来自动更新一直失败，提示网络异常，是正常的吗

**Comment by mscststs** [comment]
是不正常的，可能你的网络到github或者gitee的存在问题。

我回头有空打个最新的release吧

**Comment by a08381** [comment]
> 是不正常的，可能你的网络到github或者gitee的存在问题。
> 
> 我回头有空打个最新的release吧

用你打的这个0.18没有问题，说起来我打包的时候遇到了不少状况，最后删除了package-lock.json和yarn.lock

**Comment by a08381** [comment]
问题出在你使用的fsevents依赖用的是fsevents@^1.1.2，然后自动给装了一个1.1.3，但是我的系统需要2.x以上的fsevents

**Comment by a08381** [comment]
fsevents这个依赖好像只被webpack-dev-server需要，所以打包程序可以正常运行

**Comment by a08381** [comment]
使用仓库原本的lock文件后强制安装fsevents2.1.2并重新编译之后恢复正常了，问题完结。

![屏幕快照 2020-04-23 上午1 43 29](https://user-images.githubusercontent.com/2505002/80015371-33953000-8504-11ea-932a-9637f083d1c3.png)

[bls-0.1.22.dmg](https://www.lanzous.com/ibsllyf)
