### ISSUE TITLE
运行一段时间后就会白屏卡死

### ISSUE THREAD

**Issue by G-Cutemon** [mscststs/BLS#16]
打开控制台时会出现如下报错并触发断点
[这是个图](https://photo.weibo.com/2064501881/photos/large/photo_id/4498722372321473/album_id/3458601028964313)

**Comment by mscststs** [comment]
问题已知，正在想怎么解决

**Comment by mscststs** [comment]
新版已经尝试解决了一下内存泄露的问题，可以试一下
