### ISSUE TITLE
求一个油猴脚本

### ISSUE THREAD

**Issue by youth1996** [mscststs/BLS#2]
油猴那个脚本（直播界面更换头衔）好久没写出来，自己尝试根据勋章增强编写失败
api.live.bilibili.com/i/ajaxTitleInfo?had=1这个api是头衔界面的had=1应该是已拥有，然后api.live.bilibili.com/i/ajaxWearTitle是佩戴头衔的api，需要提交id和cid，cid默认是1，升级后为2（依次）。有了这些api，求大佬有时间更新一下（实在是没看到你的邮箱只能这样提交issues了）

**Comment by mscststs** [comment]
近期

**Comment by youth1996** [comment]
谢谢，灰常感谢

**Comment by mscststs** [comment]
@youth1996 写好了。。。[greasyFork](https://greasyfork.org/zh-CN/scripts/370844-bilibili-%E7%9B%B4%E6%92%AD%E9%97%B4%E5%A4%B4%E8%A1%94%E5%A2%9E%E5%BC%BA)

**Comment by youth1996** [comment]
好的。感谢
