### ISSUE TITLE
exe安装包链接已经失效，请求补档

### ISSUE THREAD

**Issue by KokoronoSikima** [mscststs/BLS#20]

**Comment by mscststs** [comment]
嗯？我看3.1 的 release 下面挂的exe 能用呀

**Comment by KokoronoSikima** [comment]
抱歉，刚刚检查了下是下载器的问题，不小心用迅雷下的，用chrome就可以


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mscststs"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 下午3:48
收件人:&nbsp;"mscststs/BLS"<BLS@noreply.github.com&gt;;
抄送:&nbsp;"追风少年灰酱"<408261229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mscststs/BLS] exe安装包链接已经失效，请求补档 (#20)





 
嗯？我看3.1 的 release 下面挂的exe 能用呀

**Comment by mscststs** [comment]
ok
