### ISSUE TITLE
问一下,0.3.7 版本

### ISSUE THREAD

**Issue by langxingzhou** [mscststs/BLS#21]
0.3.7 版本的 两个解压包,BLS-0.3.7.zip  和  BLS-0.3.7.tar.gz 请问是解压后放在哪个路径下?我安装路径放进去后没有反应

**Comment by mscststs** [comment]
tar和zip 是源码包，无需下载，只需要找到最近的 0.3.1 的 exe ，下载安装之后执行检查更新，让其自动升级即可

**Comment by langxingzhou** [comment]
我按了检查更新,后显示这个提示信息
![提示](https://user-images.githubusercontent.com/58836534/86103358-3eb1a100-baef-11ea-92e3-a8a25364fc74.jpg)

**Comment by mscststs** [comment]
你的版本太低了，去 0.3.1 重新下载一个 exe

**Comment by mscststs** [comment]
https://github.com/mscststs/BLS/releases/tag/0.3.1

**Comment by langxingzhou** [comment]
谢谢
