### ISSUE TITLE
BUG：设置了房间号但是提示的信息与房间号不匹配

### ISSUE THREAD

**Issue by Moomesy** [mscststs/BLS#3]
昨天下载的，设置了房间号369，正常连接了
今天早上来打开后，设置了房间号369，提示连接273849成功

有两个问题
1. 房间号没有保存
2. 房间号与我填写的不符

**Comment by mscststs** [comment]
别逗了，369是短号，短号房间都有长号

**Comment by Moobusy** [comment]
不是的， 关注人数也不对

**Comment by mscststs** [comment]
那个是人气值

**Comment by Moobusy** [comment]
嗯，这个我刚又试了次，确实是我看错了
但是另外一个问题确实存在
房间号没保存，调度响应里的设置也没保存

**Comment by mscststs** [comment]
房间号和调度响应里的设置保存没用，以后也不会加。
