### ISSUE TITLE
Error: connect ECONNREFUSED 0.0.0.0: 443

### ISSUE THREAD

**Issue by DeonWinchester** [mscststs/BLS#6]
macoS Mojave 10.14

生成了安装包然后登录的时候报这个错

**Comment by mscststs** [comment]
0.0.0.0拒绝了访问？这个错误还真没法推断出来是什么问题。疑似DNS挂了？

可以尝试点开这个Error，然后截图一下调用栈，也许能看出来是哪一步报的错

**Comment by mscststs** [comment]
我在虚拟机上跑了一下OSX 10.10，打包出来了一个dmg，测试没有发现问题，见[release](https://github.com/mscststs/BLS/releases/tag/0.1.8) ，你可以尝试一下这个版本。如果仍有问题，可以继续补充一些详细信息

**Comment by DeonWinchester** [comment]
谢谢。用了你打包的，还是一样的问题，我觉得应该是我环境的问题，我换一台Windows电脑是可以运行的。
