### ISSUE TITLE
关于舰长亲密度领取

### ISSUE THREAD

**Issue by Kasiansk** [mscststs/BLS#7]
在最近我发现 舰长亲密度系统领取不了

**Comment by mscststs** [comment]
黑屋了？

**Comment by Kasiansk** [comment]
> 黑屋了？
并没有 我挂了四个账户 其中两个实测是进入小黑屋 但是另外两个 没有进入小黑屋 但是软件并不能让另外没进小黑屋的账户 领取亲密度

**Comment by Kasiansk** [comment]
> > 黑屋了？
> > 并没有我挂了四个账户其中两个实测是进入小黑屋但是另外两个没有进入小黑屋但是软件并不能让另外没进小黑屋的账户领取亲密度

对了 我有一个问题我不能确定 是不是舰长亲密度服务器出了问题 就在 今天 貌似又没有舰长亲密度

**Comment by mscststs** [comment]
> 对了 我有一个问题我不能确定 是不是舰长亲密度服务器出了问题 就在 今天 貌似又没有舰长亲密度

有可能，因为是第三方开发者提供的服务器，最近可能不太稳定。

如果有其他的舰长监听服务器的话也欢迎告诉我，我可以添加到BLS中

**Comment by Kasiansk** [comment]
如果我 找到其他的监听服务器 会告诉你的
